

name: 'cloud_transform_dbt'
version: '1.3.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'cloud_transform_dbt'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  +schema: sales
  

models:
  cloud_transform_dbt:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      warehouse:
        +schema: warehouse
    
