version: 2

models:
  - name: dim_territory
  - name: dim_product
  - name: dim_production__product_category
  - name: dim_production__product_subcategory
  - name: dim_employee
  - name: dim_customer
  - name: fct_sales
